http:
  host: "localhost"
  port: 8080

db:
  mysql:
    type: "mysql"
    host: "us-cdbr-east-04.cleardb.com"
    port: 3306
    database: "heroku_0433cf592b52eb5"
    username: "b9eb82d1b8707c"
    password: "e514cc49"

  test:
    type: "mysql"
    host: "localhost"
    port: 3306
    database: "salepipe"
    username: "salepipe"
    password: "12345678"
    logging: false

auth:
  signup:
    expiresIn: "24" # hours
  forgotPassword:
    expiresIn: "24" # hours
  secret: "12345"
  signOptions:
    expiresIn: "0.5d"

email:
  apiKey: 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
  defaultSender: igor.shevk@gmail.com
  templates:
    signupEmailPrepareId: d-4c6c1af94ab34713903951a211405c56
    signupEmailConfirmId: d-3f4e466b517747a9aae6f14ab49c4254
    forgotPasswordRequestId: d-a8dad92a53344658a48f62e3a28b113d
    changePasswordRequestId: d-fbdae86eae784583afc4ba3bb7544ce4
    changedPasswordId: d-418359d170264e92b4efae046215d74d
    createdAccountId: d-c82dfa89615d4ae586e556ef32ecef93
    verifiedAccountId: d-396d1868d6674a5196a4a3590420c708
