http:
  host: "localhost"
  port: 8080

db:
  mysql:
    type: "mysql"
    host: "us-cdbr-east-04.cleardb.com"
    port: 3306
    database: "heroku_45e58739a7033b3"
    username: "b0ce01cf4adc4f"
    password: "07f7c486"

  test:
    type: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "test"
    username: "devblock"
    password: "Abc123456"
    logging: false

auth:
  secret: "12345"
  signOptions:
    expiresIn: "0.5d"
