http:
  host: "localhost"
  port: 8080

db:
  mysql:
    type: "mysql"
    host: "us-cdbr-east-04.cleardb.com"
    port: 3306
    database: "heroku_0433cf592b52eb5"
    username: "b9eb82d1b8707c"
    password: "e514cc49"

  test:
    type: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "test"
    username: "devblock"
    password: "Abc123456"
    logging: false

auth:
  secret: "12345"
  signOptions:
    expiresIn: "0.5d"

email:
  apiKey: secret
  defaultSender: sender@gmail.com
  templates:
    forgotPasswordRequestId: forgotPasswordId
    changePasswordRequestId: changePasswordRequestId
    changedPasswordId: changedPasswordId
    createdAccountId: createdAccountId
    verifiedAccountId: verifiedAccountId
