http:
  host: "localhost"
  port: 8080

db:
  mysql:
    type: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "test"
    username: "devblock"
    password: "Abc123456"

  sqlite:
    type: "sqlite"
    database: "sqlite.db"
