http:
  host: "localhost"
  port: 8080

db:
  mysql:
    type: "mysql"
    host: "us-cdbr-east-04.cleardb.com"
    port: 3306
    database: "heroku_0433cf592b52eb5"
    username: "b9eb82d1b8707c"
    password: "e514cc49"

  test:
    type: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "test"
    username: "devblock"
    password: "Abc123456"
    logging: false

auth:
  signup:
    expiresIn: "24"   # hours
  forgotPassword:
    expiresIn: "24"   # hours
  secret: "12345"
  signOptions:
    expiresIn: "0.5d"

email:
  apiKey: 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
  defaultSender: nghia.ngd28@gmail.com
  templates:
    signupEmailPrepare: d-aee9f6dd0d124980aeaec7a1e578bbe7
    signupEmailConfirm: d-268eae88c6b6493eabe1454aa4106a38
    forgotPasswordRequestId: d-828796a5641248218dd0fb663d6987c8
    changePasswordRequestId: d-17eb9d4fb5cb4f0eb414ea5f53cc9480
    changedPasswordId: d-e63325a15e1e4ceda64868dec45442b1
    createdAccountId: d-f7b7b3d72c0b4edcbd2d13ab71106c71
    verifiedAccountId: d-4461a24676b24ebcb5eb20a2f69d398c
