http:
  host: "localhost"
  port: 8080

db:
  mysql:
    type: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "test"
    username: "devblock"
    password: "Abc123456"

  test:
    type: "mysql"
    host: "127.0.0.1"
    port: 3306
    database: "test"
    username: "devblock"
    password: "Abc123456"
    logging: false

auth:
  secret: "12345"
  signOptions:
    expiresIn: "0.5d"
